from . import project_extension
from . import res_config_settings
from . import sale_order_extension
from . import stock_picking_extension
from . import crm_lead
from . import sale_order_project_wizard
from . import project_color
from . import project_obra_estado
from . import project_provincia
from . import project_LnArti
from . import project_ObraTipo
from . import project_Ubi
from . import syusro
from . import project_cartel_obra